### PR TITLE
change WARNING to NOTICE

### PR DESCRIPTION
**Pull request by jimscarver**

### CODE REVIEW

**Comment by jimscarver** [comment]
done with @dckc and @David405

**Comment by David405** [comment]
@dckc we are using this PR to update changes to some styles. As regarding the database dump, it was an error, it somehow broke viewing data on rewards-test.

**Comment by dckc** [comment]
> we are using this PR to update changes to some styles.

Why? Why not make a separate PR?

If you're going to expand the scope of this one, at least change the title.

**Comment by dckc** [comment]
we cherry-picked this to a history without the DB dump

**Pull request closed without merging**
